baseURL = "https://pid.ren"
title = "pid.ren"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = "G-N0FVQSX2JC"
enableRobotsTXT = true
copyright = "&copy; Copyright 2021, Ren Lee"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90

# Configuration Features
[params]
  description = "pid.ren"      # Your meta description of the site
  header_title = "Ren Lee"                 # Your header title
  header_subtitle = "Site Reliability Engineer @ Arista Networks. Minimalist, ultralight backpacker, avid reader, and a cat-mom. All thoughts/opinions are my own. (She/her)" # Your header subtitle
  home_image = "/images/profile.jpg"          # Path to header image starting from the static directory
  recent_posts = 1                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "https://github.com/pidren"        # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/pidren"
  [[params.social]]
    fa_icon = "fas fa-at fa-1x"
    href = "ren@pid.ren"
